### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Arjuman23** [dreji18/Bio-Epidemiology-NER#2]
Hey! Great work with the Bio-EN model. Getting 41 entities out of any medical/clinical document is truly amazing! 
But there is one observation that I made.
The memory consumed by the model to NER a document increases after every run. Is this memory leak a known issue?
Is there some modification that can be done in the model to avoid this??

Thanks

**Comment by dreji18** [comment]
Thanks @Arjuman23 for your feedback. Could you give a bit more context about this problem? Is it when you are calling the model in a batch?

**Comment by Arjuman23** [comment]
Precisely. 
This was the case even when it was dockerized and tested via postman. The docket stats kept changing per run I.e, the memory consumption increased per run. I was expecting the size to go back to the original size after each run, but that didn't happen.

**Comment by dreji18** [comment]
Could you make it an API and try calling it, also I would say it's better you deploy the model somewhere and call if it's working for a batch. Which compute are you using GPU or CPU?

**Comment by Arjuman23** [comment]
Tried and tried.
Is this a known issue to you? Like, have you faced it personally??

**Comment by dreji18** [comment]
Could you help me understand your issue better:
1. are you running this model on GPU?
2. have you tried converting it into an API and hosting it on a server?
3. Which deployment service you used?
4. What is the typical batch size you feed to the model?
5. When you say memory leak, could you paste the error you are getting? is it crashing after some point or getting failed for specific batches.?

I haven't run this biomedical model in production, so I cannot comment here on the production-level performance. But there are instances my other models get crashed in production with memory issues. I got it resolved by adjusting the batch size based on the other dependencies (like other models, data volume etc.) 

Also, I deployed the model in the Azure cloud and called it an endpoint, so these issues are resolved there since Azure automatically scales up and scales down based on the volume.

**Comment by Arjuman23** [comment]
The model doesn't run on GPU. It has been converted into an API and hosted on various servers, and the entire model and its services have been dockerized and run. The typical batch size would be 1000.
And when I say memory leak, it doesn't mean that it's throwing an error. It just means that the memory consumption of the model doesn't return to its original size after each run.
Again, the model doesn't crash, it just consumes more and more memory after each process.

**Comment by dreji18** [comment]
Interesting, I am not sure why the servers are not auto-adjusting the load, ideally it should.
